/**:
  ros__parameters:
    NAMESPACE: /ego_racecar
    OPPONENT_NAMESPACE: /opp_racecar
    GLOBAL_PATH_TOPIC: /ego_racecar/waypoints
    DRIVE_TOPIC: /drive
    COLOR: green

    IS_VECTOR_COST: False
    PROGRESS_RESET_RATIO: 0.75
    STEERING_INCREMENT: 0.6109
    ACCELERATION_INCREMENT: 0.25
    ACTION_LST: [-1.0, -1.0, 
                 -1.0, 0.0,
                 -1.0, 1.0, 
                  0.0, -1.0,
                  0.0, 0.0,
                  0.0, 1.0,
                  1.0, -1.0, 
                  1.0, 0.0,
                  1.0, 1.0, 
                  1.0, -0.5,
                  1.0, 0.5]
                  
    MAX_SPEED: 1.0  # m/s
    ACTION_INTERVAL: 0.25 # seconds
    RECEDING_HORIZON: 1.5 # seconds
    DT: 0.25

    # ACTION_INTERVAL: 1.0 # seconds
    # RECEDING_HORIZON: 5.0 # seconds
    # DT: 1.0

    # size for calculations, radial (width) and frontal (length) axes
    LF: 1
    LR: 1

    # how close bike center points are in pixels to count as collision
    COLLISION_RADIUS: 2
    PROXIMITY_SPREAD: 2.0
    BOUNDS_SPREAD: 5

    PROGRESS_WEIGHT: 1
    BOUNDS_WEIGHT: 100
    PROXIMITY_WEIGHT: 10
